spring.application.name=women-empowerment
# ==============================
# MySQL Database Configuration
# ==============================
#spring.datasource.url=jdbc:mysql://localhost:3306/women_empowerment_db
spring.datasource.url=jdbc:mysql://localhost:3306/women_empowerment_db?useUnicode=true&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=Atal7201@Z
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA / Hibernate Configuration
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==============================
# SQL Initialization
# ==============================
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

# ==============================
# Server Port
# ==============================
server.port=8080

# ==============================
# CORS (Allow all for dev)
# ==============================
spring.web.cors.allowed-origins=*